<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title><?= $page->escHtml($title); ?></title>
    <link rel="stylesheet" type="text/css" href="<?= $page->escAttr($app->url("/resource/styles/main.css")); ?>" />
    <script type="text/javascript" src="<?= $page->escAttr($app->url("/resource/jscripts/main.js")); ?>" data-main=""></script>
</head>
<body>
<div id="wrap">

